### ISSUE TITLE
[Bug]: Loading extensions failed. Unable to find product_subscription extension type

### ISSUE THREAD

**Issue by OlajumokeFaj** [Shopify/shopify-cli#2147]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

There should be a prompt to select an extension and a new .env file should be created after the selection.

### Actual behavior

It failed while attempting to load extensions for extension type - product_subsctiption

```
⠏ Loading your extensions…
⠦ Loading your extensions…
⠙ Loading your extensions…
⠹ An unexpected error occurred on Shopify.
⠸ Loading your extensions…
⠹ Loading your extensions…
⠇ Loading your extensions…
⠼ Loading your extensions…
⠹ Loading your extensions…
⠇ Loading your extensions…
⠇ Loading your extensions…
⠏ Loading your extensions…
✗ Loading your extensions…
```
`┏━━ Task Failed: Loading your extensions…`

### Stack trace

```shell
NoMethodError: undefined method `map' for nil:NilClass
┃ 
┃           app["extensionRegistrations"].map do |registration|
┃                                        ^^^^
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:24:in `block in extensions_owned_by_organization'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:23:in `each'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:23:in `flat_map'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:23:in `extensions_owned_by_organization'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:16:in `block in extensions_from_organizations'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:15:in `each'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:15:in `flat_map'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:15:in `extensions_from_organizations'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/tasks/get_extensions.rb:9:in `call'
┃ 	from /Shopify/shopify-cli/lib/shopify_cli/task.rb:8:in `call'
┃ 	from /Shopify/shopify-cli/lib/project_types/extension/forms/questions/ask_registration.rb:41:in `block in load_registrations'
┃ 	from /Shopify/shopify-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:137:in `block in run'
┃ 	from/Shopify/shopify-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:92:in `with_stdin_masked'
┃ 	from /Shopify/shopify-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:125:in `run'
┃ 	from /Shopify/shopify-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:48:in `block in initialize'
```

### Reproduction steps

1. Create an app and product subscription extension then push the extension
2. Create another app and product subscription extension and rename the env file of the extension
3. Run`Shopify extension connect`

### Operating System

Mac OS

### CLI version (run `shopify version` if you're not sure)

shopify version

### Shell

zsh

**Comment by amcaplan** [comment]
Hi @OlajumokeFaj, thanks for submitting this report! I've managed to reproduce, and it seems to be a problem with the Shopify Partners backend, not the CLI itself.

[Bugsnag link](https://app.bugsnag.com/shopify/partnersapp/errors/61bcbddf3199790007e98c38?filters[event.since]=30d&filters[error.status]=open) (for Shopify use)

Oddly other extension types work fine, it seems to be specifically for product subscription as mentioned.

**Comment by OlajumokeFaj** [comment]
It is because of a naming mismatch. The name used in CLI does not match what is being used in Core.

**Comment by amcaplan** [comment]
🤔 that is definitely a problem. I guess I'm wondering a few things:

1. Is this still a bug in the Partners API? Should this be a 400 with descriptive error instead of a 500?
2. I need to dig a bit deeper and understand how we could translate the keys, as there will be plenty of existing extensions we'll need to support, and this is definitely the convention in the CLI.
3. By the way, what is the "correct" name? Is [this](https://github.com/Shopify/partners/blob/21a1f413aa9ad9d97abc8a7ba165029e23b0280e/app/graphql/graph_api/cli/extensions/type.rb#L11) what we're looking for?
4. How did this happen? How can we prevent it in the future?

**Comment by OlajumokeFaj** [comment]
Yes, the name used in core is Subscription management but product subscription was its initial name, as far as I know. @pt2pham, could you share an input on the best direction to fix the issue? Is the mismatch to be accommodated in core or should it be fixed in CLI. It seems to be linked to the filter applied on the fetched extensions https://github.com/Shopify/shopify/pull/326527

**Comment by pt2pham** [comment]
👋🏻 Are we sending a request to Partners with `product_subscription` as the specification_identifier rather than `subscription_management` Jumoke? My first instinct would be to send the correct name to Core, but I'll have to dig into it.

**Comment by campmedia** [comment]
This issue persists for me. Same issue reported here: https://github.com/Shopify/shopify-cli/issues/2234
